### ISSUE TITLE
Allow colour output to interop with other console writers

### ISSUE THREAD

**Issue by adamchester** [serilog/serilog-sinks-literate#17]
I often use this sink to get great readable console output during my unit tests. However, I also often have multiple test threads running at the same time. This causes the console output to be interleaved between the multiple threads, making it hard to read and understand what just happened. Sometimes the colours are in the wrong place... sometimes the text from one process is interleaved with text from the literate sink.

One common way to solve this issue is to simply allow the caller/user to provide an `object` which can be [used as the `lock`](https://github.com/serilog/serilog-sinks-literate/blob/8b281b750f4a36008d972f108d06dcf87ab04f97/src/Serilog.Sinks.Literate/Sinks/Literate/LiterateConsoleSink.cs#L90). All console writers share this lock object instance and this ensures that a each log event is written to the console write as an atomic operation. 

The downside of course is that each thread may end up getting blocked longer and more often, however at least now the console output makes sense, and the user explicitly decided to opt in to this anyway by providing the locks.

**Comment by adamchester** [comment]
P.s. The dotnet / windows APIs for console and colour output are a real pain here. We might want to [prioritise cross-platform ansi terminal output instead](https://github.com/serilog/serilog-sinks-literate/issues/9#issuecomment-255951085), since this provides a way for the entire message (including colour escape codes) to be composed prior to being written.

**Comment by nblumhardt** [comment]
The ANSI option might be a more widely useful way around this one, since there's good support in Win10 and it expands the color palette..

Slightly OT, but wondering what you think about doing an overhaul/unification of all the various console sinks. Literate console should really be the default; what about if we were to merge it (logically, not directly) into Serilog.Sinks.Console? With custom palette support, it could also completely replace Serilog.Sinks.ColoredConsole...

At the same time, supporting the `{Message:l}` option we've been talking about would unify the literate console formatting with other sinks (since literate doesn't bother with string quoting etc.).

Seems like it'd be a substantial chunk of work, might be hard to get traction on, but in an ideal world....?

**Comment by adamchester** [comment]
Yeah 👍 on overhaul/unification... I can imagine myself trying to help out on such an adventure.

I really want `{Properties}` and xplat colours and faster rendering and colour themes and... (I want it all).

Let's talk feature plans elsewhere?

**Comment by nblumhardt** [comment]
Yes, sounds good. Opened https://github.com/serilog/serilog-sinks-console/issues/7, will close this one, optimistically :-)
